version: '3.7'

services:
  sqldata:
    image: postgres

  server:
    image: server:${TAG:-latest}
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      - sqldata

  client:
    image: client:${TAG:-latest}
    build:
      context: .
      dockerfile: Client/Dockerfile
    depends_on:
      - server