version: '3.7'

services:
  sqldata:
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"

  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "47001:81"